services:
  ripperdocshop.api:
    image: ripperdocshop.api
    build:
      context: .
      dockerfile: RipperdocShop.Api/Dockerfile

  ripperdocshop.web:
    image: ripperdocshop.web
    build:
      context: .
      dockerfile: RipperdocShop.Web/Dockerfile
      
